name: Arch Linux PKGBUILD builder action
description: Builds an validates PKGBUILD definition

branding:
  icon: triangle
  color: blue

inputs:
  dictionary:
    description: >-
      Path to DIRECTORY containing the pkgbuild dictionary
      Assumes the directory is the name of package, ie /path/to/dictionary/
    required: true
  target:
    description: >-
      Validation target.
      Can be one of: "pkgbuild", "srcinfo", "run"
    required: true
    default: 'pkgbuild'
  command:
    description: >-
      Command to run after package installation.
      Used when target=run
    required: false
  debug:
    description: Turns debugging on
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.target }}
    - ${{ inputs.dictionary }}
    - ${{ inputs.command }}
    - ${{ inputs.debug }}
